# automatically generated by the FlatBuffers compiler, do not modify

# namespace: tflite


class AssociatedFileType(object):
    UNKNOWN = 0
    DESCRIPTIONS = 1
    TENSOR_AXIS_LABELS = 2
    TENSOR_VALUE_LABELS = 3
    TENSOR_AXIS_SCORE_CALIBRATION = 4
    VOCABULARY = 5
    SCANN_INDEX_FILE = 6
