# automatically generated by the FlatBuffers compiler, do not modify

# namespace: tflite

import flatbuffers
from flatbuffers.compat import import_numpy

np = import_numpy()


class BertTokenizerOptions(object):
    __slots__ = ["_tab"]

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = BertTokenizerOptions()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsBertTokenizerOptions(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)

    @classmethod
    def BertTokenizerOptionsBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(
            buf, offset, b"\x4D\x30\x30\x31", size_prefixed=size_prefixed
        )

    # BertTokenizerOptions
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # BertTokenizerOptions
    def VocabFile(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from tflite.AssociatedFile import AssociatedFile

            obj = AssociatedFile()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # BertTokenizerOptions
    def VocabFileLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # BertTokenizerOptions
    def VocabFileIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0


def BertTokenizerOptionsStart(builder):
    builder.StartObject(1)


def Start(builder):
    return BertTokenizerOptionsStart(builder)


def BertTokenizerOptionsAddVocabFile(builder, vocabFile):
    builder.PrependUOffsetTRelativeSlot(
        0, flatbuffers.number_types.UOffsetTFlags.py_type(vocabFile), 0
    )


def AddVocabFile(builder, vocabFile):
    return BertTokenizerOptionsAddVocabFile(builder, vocabFile)


def BertTokenizerOptionsStartVocabFileVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)


def StartVocabFileVector(builder, numElems):
    return BertTokenizerOptionsStartVocabFileVector(builder, numElems)


def BertTokenizerOptionsEnd(builder):
    return builder.EndObject()


def End(builder):
    return BertTokenizerOptionsEnd(builder)


import tflite.AssociatedFile

try:
    pass
except:
    pass


class BertTokenizerOptionsT(object):

    # BertTokenizerOptionsT
    def __init__(self):
        self.vocabFile = None  # type: List[tflite.AssociatedFile.AssociatedFileT]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        bertTokenizerOptions = BertTokenizerOptions()
        bertTokenizerOptions.Init(buf, pos)
        return cls.InitFromObj(bertTokenizerOptions)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos + n)

    @classmethod
    def InitFromObj(cls, bertTokenizerOptions):
        x = BertTokenizerOptionsT()
        x._UnPack(bertTokenizerOptions)
        return x

    # BertTokenizerOptionsT
    def _UnPack(self, bertTokenizerOptions):
        if bertTokenizerOptions is None:
            return
        if not bertTokenizerOptions.VocabFileIsNone():
            self.vocabFile = []
            for i in range(bertTokenizerOptions.VocabFileLength()):
                if bertTokenizerOptions.VocabFile(i) is None:
                    self.vocabFile.append(None)
                else:
                    associatedFile_ = tflite.AssociatedFile.AssociatedFileT.InitFromObj(
                        bertTokenizerOptions.VocabFile(i)
                    )
                    self.vocabFile.append(associatedFile_)

    # BertTokenizerOptionsT
    def Pack(self, builder):
        if self.vocabFile is not None:
            vocabFilelist = []
            for i in range(len(self.vocabFile)):
                vocabFilelist.append(self.vocabFile[i].Pack(builder))
            BertTokenizerOptionsStartVocabFileVector(builder, len(self.vocabFile))
            for i in reversed(range(len(self.vocabFile))):
                builder.PrependUOffsetTRelative(vocabFilelist[i])
            vocabFile = builder.EndVector()
        BertTokenizerOptionsStart(builder)
        if self.vocabFile is not None:
            BertTokenizerOptionsAddVocabFile(builder, vocabFile)
        bertTokenizerOptions = BertTokenizerOptionsEnd(builder)
        return bertTokenizerOptions
