# automatically generated by the FlatBuffers compiler, do not modify

# namespace: tflite

class ContentProperties(object):
    NONE = 0
    FeatureProperties = 1
    ImageProperties = 2
    BoundingBoxProperties = 3
    AudioProperties = 4
