# automatically generated by the FlatBuffers compiler, do not modify

# namespace: tflite

class ProcessUnitOptions(object):
    NONE = 0
    NormalizationOptions = 1
    ScoreCalibrationOptions = 2
    ScoreThresholdingOptions = 3
    BertTokenizerOptions = 4
    SentencePieceTokenizerOptions = 5
    RegexTokenizerOptions = 6
